module.exports.COMMANDS = {
  ON: 'on',
  OFF: 'off',
  TOGGLE: 'toggle',
  T: 't',
  DND_STATUS: 'dnd-status',
  DND_TOGGLE: 'dnd-toggle',
  DND_T: 'dnd-t',
  DND_ON: 'dnd-on',
  DND_OFF: 'dnd-off',
  HIDE_DESKTOP_TOGGLE: 'desk-toggle',
  HIDE_DESKTOP_T: 'desk-t',
  HIDE_DESKTOP_ON: 'desk-on',
  HIDE_DESKTOP_OFF: 'desk-off',
  HIDE_MENUBAR_TOGGLE: 'menu-toggle',
  HIDE_MENUBAR_T: 'menu-t',
  IN_ZOOM: 'zoom',
  NOTIFY: 'notify',
  LIST: 'list',
  HELP: 'help',
}
